### ISSUE TITLE
dataset_metadata.yaml not correctly updated when deprecated: true

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#4873]
`workgroup_access` in the `dataset_metadata.yaml` files doesn't get updated correctly to `[]` nor does `default_table_workgroup_access` get set to `workgroup:mozilla-confidential` when `deprecated: true` is set in one of the query `metadata.yaml` files.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2469)

**Comment by whd** [comment]
I think in the PR this isn't an issue, but the intent should be for `default_table_workgroup_access` to get set to whatever `workgroup_access` was as opposed to `workgroup:mozilla-confidential` specifically. For instance, a deprecated table in https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/contextual_services/dataset_metadata.yaml should wind up with the generated dataset metadata looking like:
```yaml
workgroup_access: []
default_table_workgroup_access:
- role: roles/bigquery.dataViewer
  members:
  - workgroup:contextual-services
```
